list<string> fn = new list<string> {'Alex', 'Phil', 'Jay'};
list<string> ln = new list<string> {'Doe', 'Dun','Gram'};
list<string> em = new list<string> {'abc@xyz.com', 'def@xyz.com', 'qwe@xyz.com'};
//EmployeeDetails.forInformationTechnology(fn, ln, em);

EmployeeDetails.forFinanceAndAccounting(fn, ln, em);

EmployeeDetails.forProductionEngineering(fn, ln, em);

EmployeeDetails.forQualityAssurance(fn, ln, em);
